name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish-crates-io:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch main branch
        run: git fetch origin main

      - name: Ensure tag is on main
        run: |
          if git merge-base --is-ancestor origin/main "$GITHUB_SHA"; then
            echo "Tag commit is on main (or descendant)."
          else
            echo "Tag is not on main; skipping publish."
            exit 1
          fi

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Publish crate
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --token "$CARGO_REGISTRY_TOKEN"

  github-release:
    name: Create GitHub Release
    needs: publish-crates-io
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true


